collections:
- name: community-general-8.4.0.tar.gz
  version: 8.4.0
- name: ansible-posix-1.5.4.tar.gz
  version: 1.5.4
- name: kubernetes-core-3.0.1.tar.gz
  version: 3.0.1
- name: freeipa-ansible_freeipa-1.12.0.tar.gz
  version: 1.12.0
- name: ansible-utils-3.1.0.tar.gz
  version: 3.1.0
- name: techno_tim-k3s_ansible-1.0.0.tar.gz
  version: 1.0.0
