---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deepthot-org
  namespace: traefik
spec:
  secretName: deepthot-org-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: deepthot.org
  dnsNames:
  - "deepthot.org"
  - "*.deepthot.org"
  - "*.local.deepthot.org"