---
# This playbook deploys the whole application stack in this site.

- name: global configuration
  hosts: all
  collections:
    - freeipa.ansible_freeipa
  become: true
  remote_user: ansible
  vars:

#  tasks:
#    - include_vars:
#        dir: inventory/vars/all

  roles:
    - machines/common
