---

- hosts: "eddie"
  remote_user: root
  gather_facts: no

  vars:
    clone: ubuntu-cloud
    api_host: eddie
    vmname: awx-host
    newid: 300
    IP: 192.168.42.30
    memory: 16384
    cores: 4
    size: 20G
    mytags:
      - awx
      - ipa
  
  roles:
    - proxmox/create_vm

- hosts: "awx-host"
  remote_user: ansible
  become: true
  gather_facts: yes

  roles:
    - machines/ipa
    - techno_tim.k3s_ansible.download
    - techno_tim.k3s_ansible.k3s_server
    - metallb
    - geerlingguy.helm
    - install_awx

