---
# This playbook deploys the whole application stack in this site.

- name: set up kubernetes cluster
  hosts: all
  remote_user: ansible
  become: true
  collections:
    - freeipa.ansible_freeipa

  vars:
    docker_packages_state: absent
    kubernetes_version: '1.29.1'
    kubernetes_apt_repository: 'deb [signed-by=/etc/apt/trusted.gpg.d/k8s.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
    kubernetes_allow_pods_on_control_plane: true
    kubernetes_pod_network:
      # Flannel CNI.
      # cni: 'flannel'
      # cidr: '10.244.0.0/16'
      #
      # Calico CNI.
      cni: 'calico'
      cidr: '10.244.0.0/16'
      #
      # Weave CNI.
      # cni: 'weave'
      # cidr: '192.168.0.0/16'

  roles:
    - machines/common
    - machines/pre_docker
    - geerlingguy.containerd
    - machines/kubernetes
    - role: geerlingguy.kubernetes
      vars:
        kubernetes_version_kubeadm: '{{kubernetes_version}}'
