---

- hosts: heartogold
  remote_user: root
  gather_facts: no
  any_errors_fatal: true

  vars:
    clone: ubuntu-cloud
    api_host: heartogold
  
  tasks:
    - name: "create nodes"
      vars:
        vmname: "{{item.vmname}}"
        newid: "{{item.newid}}"
        mytags: "{{item.mytags}}"
        cores: "{{item.cores}}"
        memory: "{{item.memory}}"
        size: "{{item.size}}"
        storage: "{{item.storage}}"
        IP: 192.168.42.{{ item.newid | int - 400 + 20 }}
        # MAC: "12:00:00:00:00:{{ item.newid|int - 400 + 20 }}"

      ansible.builtin.include_role:
        name: proxmox/create_vm
        public: true
      loop:
        - {vmname: '{{cluster}}-cont1',newid: 401, mytags: ['k8s','ipa','control'], cores: 2, memory: 4096, size: 12G, storage: "local-lvm"}
        - {vmname: '{{cluster}}-cont2',newid: 402, mytags: ['k8s','ipa','control'], cores: 2, memory: 4096, size: 12G, storage: "local-lvm"}
        - {vmname: '{{cluster}}-cont3',newid: 403, mytags: ['k8s','ipa','control'], cores: 2, memory: 4096, size: 12G, storage: "local-lvm"}
        - {vmname: '{{cluster}}-work1',newid: 405, mytags: ['k8s','ipa','worker'], cores: 8, memory: 8192, size: 16G, storage: local-lvm}
        - {vmname: '{{cluster}}-work2',newid: 406, mytags: ['k8s','ipa','worker'], cores: 8, memory: 8192, size: 16G, storage: local-lvm}
        - {vmname: '{{cluster}}-work3',newid: 407, mytags: ['k8s','ipa','worker'], cores: 8, memory: 8192, size: 16G, storage: local-lvm}
        - {vmname: '{{cluster}}-store1',newid: 411, mytags: ['k8s','ipa','store'], cores: 2, memory: 2048, size: 300G, storage: zfs}
        - {vmname: '{{cluster}}-store2',newid: 412, mytags: ['k8s','ipa','store'], cores: 2, memory: 2048, size: 300G, storage: zfs}
        - {vmname: '{{cluster}}-store3',newid: 413, mytags: ['k8s','ipa','store'], cores: 2, memory: 2048, size: 300G, storage: zfs}
        - {vmname: '{{cluster}}-store4',newid: 414, mytags: ['k8s','ipa','store'], cores: 2, memory: 2048, size: 300G, storage: zfs}
        - {vmname: '{{cluster}}-store5',newid: 415, mytags: ['k8s','ipa','store'], cores: 2, memory: 2048, size: 300G, storage: zfs}

- hosts: "tag_k8s"
  remote_user: ansible
  become: true
  gather_facts: yes 
  name: Prepare nodes
  any_errors_fatal: true

  roles:
    - machines/ipa
    - role: techno_tim.k3s_ansible.prereq
      become: true
    - role: techno_tim.k3s_ansible.download
      become: true
    - role: techno_tim.k3s_ansible.raspberrypi
      become: true
    - role: techno_tim.k3s_ansible.k3s_custom_registries
      become: true
      when: custom_registries

- name: Setup k3s controllers
  hosts: tag_control
  gather_facts: yes
  become: true
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: techno_tim.k3s_ansible.k3s_server
      become: true

- name: Setup k3s workers
  hosts: tag_worker,tag_store
  environment: "{{ proxy_env | default({}) }}"
  any_errors_fatal: true
  roles:
    - role: techno_tim.k3s_ansible.k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: tag_control
  environment: "{{ proxy_env | default({}) }}"
  any_errors_fatal: true
  roles:
    - role: techno_tim.k3s_ansible.k3s_server_post
      become: true

- name: Storing kubeconfig in the playbook directory
  hosts: tag_control
  become: true
  environment: "{{ proxy_env | default({}) }}"
  tasks:
    - name: replace with cluster name
      replace:
        path: "/etc/rancher/k3s/k3s.yaml"
        regexp: "(default|127.0.0.1)"
        replace: "{{cluster}}"

    - name: Copying kubeconfig from {{ hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] }}
      ansible.builtin.fetch:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: ./kubeconfig
        flat: true
      when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
