---
- hosts: "eddie"
  remote_user: root
  gather_facts: false

  vars:

  tasks:
    - debug:
        var: vars

    # - name: Delete old VM
    #   any_errors_fatal: false
    #   community.general.proxmox_kvm:
    #     name: "{{vmname}}"
    #     api_user: "{{ lookup('ansible.builtin.env','PROXMOX_USER')}}"
    #     api_password: "{{ lookup('ansible.builtin.env','PROXMOX_PASSWORD') }}"
    #     api_host: eddie
    #     state: "absent"
    #     force: true
    #     timeout: 120
    
    - name: "{{vmname}}"
      vars:
        # newid: "{{ newid | omit }}"
        # newid: "{{ omit if newid is not defined else newid }}"
        # clone: "{{ omit if clone is not defined else clone }}"
        # IP: "{{ omit if IP is not defined else IP }}"

      ansible.builtin.include_role:
        name: proxmox/create_vm
        public: true

    - debug:
        var: vars

