---

- hosts: "pve"
  remote_user: root
  gather_facts: yes

  vars:
    clone: ubuntu-cloud
    api_host: pve
    vmname: testable
    memory: 8192
    cores: 4
    size: 20G
    mytags:
      - awx
      - ipa
  
  roles:
    - proxmox/create_vm

- hosts: "testable"
  remote_user: ansible
  become: true
  gather_facts: yes

  roles:
    - machines/ipa
    - techno_tim.k3s_ansible.download
    - techno_tim.k3s_ansible.k3s_server
