---
# Build a VM and install torrent on it.

- hosts: "pve"
  remote_user: root
  gather_facts: no

  vars:
    clone: deepthot-jammy
    api_host: pve
    vmname: torrent
    newid: 301
    memory: 8192
    cores: 4
    size: 16G
    mytags:
      - torrent
      - ipa
  
  roles:
    - proxmox/create_vm

- hosts: torrent
  remote_user: ansible
  become: true
  gather_facts: yes

  tasks:
    - name: Ensure deluge user has the right uid
      user:
        name: debian-deluged
        uid: 118
        home: /var/lib/deluged
        shell: /usr/sbin/nologin
        system: true
        state: present

- hosts: torrent
  remote_user: ansible
  become: true
  gather_facts: yes

  roles:
    - machines/ipa
    - openvpn
    - install_deluge
    # - filebot
