---
# Manage Packages. Pass a list of packages to install or leave empty to just update

- name: Wait for automatic system updates
  become: true
  shell: while sudo lslocks|grep -qE "/var/lib/dpkg/lock-frontend|/var/lib/apt/lists/lock"; do sleep 1; done;
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Wait for package manager (distribution specific)
  block:

    - name: Wait for apt (Debian/Ubuntu)
      apt: update_cache=yes state=present
      when: ansible_os_family == "Debian"

    - name: Wait for yum (RedHat/CentOS/Fedora)
      yum: name=dnf-automatic groups=anaconda
      when: ansible_os_family == "RedHat"

    - name: Wait for dnf (Fedora)
      dnf: name=dnf-automatic groups=anaconda
      when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

    - name: Wait for pacman (Arch Linux)
      pacman: name="@ pacman-mirrors"
      when: ansible_os_family == "Arch"

  # Fail if no matching wait task was found for the distribution
  delegate_facts: false

- name: Install packages if needed
  become: true  # Assuming root privileges are required
  package:
    name: "{{ package }}"
    state: present
  when: package is defined

- name: Packages in Correct State (distribution specific)
  block:

    - name: Update and upgrade (apt)
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"

    - name: Update and upgrade (yum)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat" and not ansible_distribution == "Fedora"

    - name: Update and upgrade (dnf)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

    - name: Update and upgrade (pacman)
      pacman:
        name: "{{ packages }}"  # Update all packages by default
        state: latest
        update_cache: yes
      when: ansible_os_family == "Arch"

- name: Reboot if Needed
  include_tasks: reboot_if_needed.yaml

