---
# configure a VM that has been created on esx

# we changed the port on the nexus repository
- name: reconfigure sources.list
  replace:
    path: /etc/apt/sources.list
    regexp: '^deb'
    replace: '# deb'
    backup: yes

- name: Deepthot Repository
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list.d/deepthot.list
    block: |
      deb http://nexus:8083/repository/ubuntu jammy main restricted
      deb http://nexus:8083/repository/ubuntu jammy-updates main restricted
      deb http://nexus:8083/repository/ubuntu jammy universe
      deb http://nexus:8083/repository/ubuntu jammy-updates universe
      deb http://nexus:8083/repository/ubuntu jammy multiverse
      deb http://nexus:8083/repository/ubuntu jammy-updates multiverse
      deb http://nexus:8083/repository/ubuntu jammy-backports main restricted universe multiverse
      deb http://nexus:8083/repository/ubuntu jammy-security main restricted
      deb http://nexus:8083/repository/ubuntu jammy-security universe
      deb http://nexus:8083/repository/ubuntu jammy-security multiverse

- name: upgrade packages
  apt:
    autoremove: yes
    state: present
    update_cache: yes
    upgrade: dist

- name: install required packages
  apt:
    state: present
    package:
      - emacs-nox
      - freeipa-client
      - autofs
      - nfs-kernel-server
      - direnv

- name: edit nsswitch to allow sss to access automount
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'automount:'
    line: "automount:\tfiles sss"

- hostname:
    name: "{{ ansible_hostname }}.deepthot.aa"
    use: systemd

- timezone:
    name: America/Phoenix
  register: timezone

- name: restart cron
  systemd:
    name: cron
    daemon_reload: true
    enabled: true
    state: restarted
  when: timezone.changed

- name: join domain
  include_role:
    name: freeipa.ansible_freeipa.ipaclient

- name: Fix Automount
  include_tasks: fix_automount.yaml

- name: Reboot if Needed
  include_tasks: reboot_if_needed.yaml
