# configure a VM that has been created on esx

#- name: reconfigure apt sources
#  include_tasks: apt_sources.yaml

#- name: Set up repository
#  include_tasks: apt_sources.yaml

- name: upgrade packages
  apt:
    autoremove: yes
    state: present
    update_cache: yes
    upgrade: dist

- name: Reboot if Needed
  include_tasks: reboot_if_needed.yaml
