---

plugin: community.general.proxmox
validate_certs: false
want_facts: true
url: http://pve.deepthot.org:8006
user: bowzer@pam
password: dogbreath
compose:
  ansible_host: proxmox_agent_interfaces[1]["ip-addresses"][0].split('/')[0]
  ansible_user: ansible
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group