---
# Reboot a machine if required by updating

- name: Check for generic reboot flag files
  find:
    paths: [/var/run, /run]
    patterns: ["reboot*.txt"]
  register: reboot_required_file

- name: Check for specific reboot indicator (Debian/Ubuntu)
  stat: path=/var/run/reboot-required
  register: reboot_required_debian

# Check for reboot required on RedHat (example)
- name: Check for reboot required on RedHat
  command: systemctl --system | grep 'reboot-pending'
  register: reboot_required_redhat
  when: ansible_os_family == "RedHat"

- name: Reboot the system (generic)
  reboot:
    msg: "Reboot initiated by Ansible due to package updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: (reboot_required_file.matched or reboot_required_debian.stat.exists) or (ansible_os_family == "RedHat" and reboot_required_redhat.rc == 0)

- wait_for: host="{{inventory_hostname}}" port=22 delay=10  timeout=300
  name: Wait for system to be stable
