---
# tasks file for deploy_metallb
  - name: Install needed packages
    ansible.builtin.include_role: 
      name: packages
    vars:
      package:
        - python3-kubernetes

  - name: Deploy MetalLB
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      apply: true
      src: https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
      wait: true

#kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
#kubectl wait deployment controller -n metallb-system --for condition=Available=True --timeout=120s 
#kubectl apply -f metal.yaml



  - name: Configure MetalLB
    kubernetes.core.k8s:
      kubeconfig: "/etc/rancher/k3s/k3s.yaml"
      apply: True
      definition:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: first-pool
          namespace: metallb-system
        spec:
          addresses:
          - 192.168.42.200-192.168.42.209
  - name: Configure MetalLB
    kubernetes.core.k8s:
      apply: True
      kubeconfig: "/etc/rancher/k3s/k3s.yaml"
      definition:
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: deepthot
          namespace: metallb-system
        spec:
          ipAddressPools:
          - first-pool
