---
version: "2"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - PORT_RANGE=30000:30010
      - WEB_APP_PORT=3000
    volumes:
      - .config:/.config
      - .assets:/.assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
