---

- name: Wait for automatic system updates
  become: yes
  shell: while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done;
  changed_when: false

- name: install required packages
  ansible.builtin.include_role: 
    name: packages
  vars:
    package:
      - python3-kubernetes
