---

- name: install environment
  include_tasks: install_environment.yaml

- name: install local-path
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'files/local-path-storage.yaml') | from_yaml_all }}"

- name: namespace
  kubernetes.core.k8s:
    kind: namespace
    name: awx
    api_version: v1
    state: present

- name: install operator
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/install_awx/files/operator') }}"
    namespace: awx
    wait: true
    wait_timeout: 600

- name: install awx
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/install_awx/files/base') }}"
    namespace: awx

# - name: install awx
#   kubernetes.core.helm:
#     chart_ref: "https://github.com/ansible/awx-operator/releases/download/2.13.1/awx-operator-2.13.1.tgz"
#     values_files: 
#       - /tmp/files/kustomization.yaml
#     create_namespace: true
#     release_name: awx
#     release_namespace: awx