---
    apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    metadata:
      name:  awx
    spec:
      service_type: clusterip
      projects_persistence: true
      # init_postgress_extra_commands: |
      #   sudo mkdir -p /var/lib/pgsql/data/userdata
      #   sudo chown -Rc 26 /var/lib/pgsql/data

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: awx
  namespace: awx
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`awx.local.deepthot.org`)
      kind: Rule
      services:
        - name: awx-service
          port: 80
      # middlewares:
      #   - name: default-headers
  # tls:
  #   secretName: deepthot-org-staging-tls

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: deepthot-org
#   namespace: awx
# spec:
#   secretName: deepthot-org-staging-tls
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   commonName: deepthot.org
#   dnsNames:
#   - "deepthot.org"
#   - "*.deepthot.org"
