---
    apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    metadata:
      name:  awx
    spec:
      service_type: clusterip

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: awx
  namespace: awx
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host('awx.local.deepthot.org')
      kind: Rule
      services:
        - name: awx-service
          port: 80
  tls:
    secretName: deepthot-org-prod-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deepthot-org
  namespace: awx
spec:
  secretName: deepthot-org-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: deepthot.org
  dnsNames:
  - "deepthot.org"
  - "*.deepthot.org"
  - "*.local.deepthot.org"