---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deepthot-org
spec:
  secretName: mailu-certificates
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: deepthot.org
  dnsNames:
  - "deepthot.org"
  - "*.deepthot.org"
  - "*.local.deepthot.org"
