---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deepthot-org-staging
spec:
  secretName: deepthot-org-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: deepthot.org
  dnsNames:
  - "deepthot.org"
  - "*.deepthot.org"
  - "*.local.deepthot.org"
  