domain: deepthot.org
hostnames:
  - mail.deepthot.org
  - smtp.deepthot.org
  - imap.deepthot.org
initialAccount:
  domain: deepthot.org
  password: chang3m3!
  username: postmaster
logLevel: DEBUG
limits:
  authRatelimit:
    ip: 100/minute;3600/hour
    user: 100/day
  messageSizeLimitInMegabytes: 200
persistence:
  size: 100Gi
  accessModes:
    - ReadWriteMany
secretKey: chang3m3!
ingress.existingSecret: deepthot-org-prod-tls
ingress.tls: false

recipientDelimiter: "+-"

networkPolicy.ingressController.namespace: traefik
app.kubernetes.io/name: traefik
app.kubernetes.io/instance: traefik
app.kubernetes.io/component: traefik
wildcardSenders: denebeim

admin.livenessProbe.enabled: false
admin.readinessProbe.enabled: false
