domain: deepthot.org
hostnames:
  - mail.deepthot.org
initialAccount:
  domain: deepthot.org
  password: "smi12les"
  username: mailadmin
logLevel: INFO
limits:
  authRatelimit:
    ip: 100/minute;3600/hour
    user: 100/day
  messageSizeLimitInMegabytes: 200
persistence:
  size: 100Gi
secretKey: "smi12les"