    - name: Clone template
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        newid: "{{ omit if newid is not defined else newid }}"
        memory: "{{ omit if memory is not defined else memory }}"
        cores: "{{ omit if cores is not defined else cores }}"
        format: "qcow2"
        node: "{{ api_host }}"
        clone: "{{clone}}"
        full: true
        boot: "order=scsi0,net0"
        ostype: "l26"
        timeout: 600
        autostart: "{{autostart}}"
        state: present
      # notify: restart on change

    - name: Resize Disk
      community.general.proxmox_disk:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: resized
        disk: scsi0
        size: "{{size}}"
      # notify: restart on change

    - name: Spin up VM
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: started
    
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
