---

    - name: Clone template
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        newid: "{{ omit if newid is not defined else newid }}"
        format: "qcow2"
        node: "{{ api_host }}"
        clone: "{{clone}}"
        full: true
        timeout: 600
        state: present

    - name: Reconfigure Machine
      community.general.proxmox_kvm:
        update: true
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        vmid: "{{omit if newid is not defined else newid}}"
        node: "{{api_host}}"
        cpu: "host"
        memory: "{{ omit if memory is not defined else memory }}"
        cores: "{{ omit if cores is not defined else cores }}"
        tags: "{{ omit if mytags is not defined else mytags }}"
        boot: "order=scsi0"
        ostype: "l26"
        autostart: "{{autostart}}"
      changed_when: false

    - name: Resize Disk
      community.general.proxmox_disk:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: resized
        disk: scsi0
        size: "{{size}}"

    - name: Spin up VM
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: started

    - wait_for: host="{{vmname}}" port=22 delay=10  timeout=600
      name: Wait for system to be stable
      changed_when: false
  
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
      changed_when: false
