---

    - name: Clone template
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        newid: "{{ omit if newid is not defined else newid }}"
        format: "qcow2"
        node: "{{ api_host }}"
        clone: "{{clone}}"
        full: true
        timeout: 600
        state: present
      register: d

    - name: result of clone
      debug:
        var: d

    - name: Reconfigure Machine
      community.general.proxmox_kvm:
        update: true
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        vmid: "{{omit if newid is not defined else newid}}"
        node: "{{api_host}}"
        kvm: true
        cpu: "host"
        memory: "{{ omit if memory is not defined else memory }}"
        cores: "{{ omit if cores is not defined else cores }}"
        tags: "{{ omit if mytags is not defined else mytags }}"
        #boot: "order=scsi0"
        hostpci: "{{omit if hostpci is not defined else hostpci}}"
        machine: "{{omit if machine is not defined else machine}}"
        ostype: "l26"
        agent: "yes"
        autostart: "{{autostart}}"
      changed_when: false

    - name: Resize Disk
      community.general.proxmox_disk:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: resized
        disk: virtio0
        size: "{{size}}"

    - name: Spin up VM
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: started
      register: result

    - wait_for: host="{{vmname}}" port=22 delay=60  timeout=600
      name: Wait for system to be stable
      when: result is changed
      changed_when: false
  
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
      changed_when: false
