---
    - name: Clone template
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        newid: "{{ omit if newid is not defined else newid }}"
        format: "qcow2"
        node: "{{ api_host }}"
        clone: "{{clone}}"
        full: true
        storage: "{{storage}}"
        timeout: 600
        state: present

    - name: "Reconfigure {{vmname}}"
      community.general.proxmox_kvm:
        update: true
        # update_unsafe: true
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        vmid: "{{omit if newid is not defined else newid}}"
        node: "{{api_host}}"
        net:
          net0: "bridge=vmbr0"
          # ipconfig0: "{{'gw=192.168.42.1,ip={{IP}}/24' if IP is defined else omit}}"
         
        kvm: true
        cpu: "host"
        memory: "{{ omit if memory is not defined else memory }}"
        cores: "{{ omit if cores is not defined else cores }}"
        tags: "{{ omit if mytags is not defined else mytags }}"

        #boot: "order=scsi0"
        hostpci: "{{omit if hostpci is not defined else hostpci}}"
        machine: "{{omit if machine is not defined else machine}}"
        vga: "std"
        ostype: "l26"
        agent: "yes"
        autostart: "{{autostart}}"
      changed_when: false

    - name: configureIP
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        node: "{{api_host}}"
        name: "{{vmname}}"
        ipconfig:
          ipconfig0: "gw=192.168.42.1,ip={{IP}}/24"
        update_unsafe: true
        update: true
      when: IP is defined

    - name: Resize Disk
      community.general.proxmox_disk:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: resized
        disk: virtio0
        size: "{{size}}"

    - name: Spin up VM
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_user: "{{api_user}}"
        api_password: "{{api_password}}"
        name: "{{vmname}}"
        state: started
      register: result

    - debug:
        var: ipaadmin_password
    - name: Create DNS record
      community.general.ipa_dnsrecord:
        record_name: "{{vmname}}"
        record_type: "A"
        record_value: "{{IP}}"
        zone_name: "{{domain}}"
        ipa_host: "ipa"
        ipa_user: "admin"
        ipa_pass: "{{ipaadmin_password}}"
      when: IP is defined
      vars:
       ansible_password: "!vault |
                          $ANSIBLE_VAULT;1.1;AES256
                          35646265373633313434643433353139373065393162323966303939623261326361636237663362
                          3761646466383734616231346163353732383861373766310a653437343038623963623036663234
                          38616331323539353463656565386164643336383939346434663764663231346137663932333831
                          3932313035373739330a333362323233346435663762613432323165663331643232643932333032
                          3430"