- name: restart on change
  community.general.proxmox_kvm: 
    api_host: "{{api_host}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
    name: "{{vmname}}"
    force: true
    state: restarted
