---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible

  roles:
    - common

- name: install ipa clients
  hosts: all
  collections:
    - freeipa.ansible_freeipa
  become: true
  remote_user: ansible

  roles:
    - ipaclient
