    api_user: "{{ lookup('ansible.builtin.env','PROXMOX_USER')}}"
    api_password: "{{ lookup('ansible.builtin.env','PROXMOX_PASSWORD') }}"
    api_host: eddie
    storage: h2gt2g-hosts
    memory: 4096
    disk: "{{storage}}:8G"
    clone: ubuntu-22.04-standard_22.04-1_amd64.tar.zst
    clone_type: full
    node: "{{api_host}}"
    password: "{{api_password}}"
    pubkey: "{{lookup('ansible.builtin.env','ANSIBLE_PUBKEY')}}"
    update: true
    autostart: false
    onboot: false
    unprivileged: true
    