---
# configure a VM that has been created on esx

- name: upgrade packages
  apt:
    autoremove: yes
    state: present
    update_cache: yes
    upgrade: dist
  become: yes

- name: install required packages
  apt:
    state: present
    package:
      - emacs-nox
      - freeipa-client
      - autofs
      - nfs-kernel-server
      - docker.io
  become: yes

- name: edit nsswitch to allow sss to access automount
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'automount:'
    line: "automount:\tfiles sss"
  become: yes

- name: set hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}.deepthot.aa"
    use: systemd
  become: yes
