---
# install kubernetes control plane

- name: install required packages
  apt:
    state: present
    package:
      - apt-transport-https
      - curl
      - containerd
      - libuser
  become: true

- name: add docker group
  group:
    name: docker
    state: present
    system: true
    local: true

- name: add users to docker group
  user:
    name: "{{item}}"
    append: yes
    groups: docker
  loop:
    - denebeim@deepthot.aa
    - ansible

- name: Add apt signing key for kubernetes packages
  apt_key:
    url: "{{item}}"
    state: present
  loop:
    - http://nexus:8082/repository/apt-kubernetes/doc/apt-key.gpg
    - http://nexus:8082/repository/apt-docker/linux/ubuntu/gpg

- name: Add deepthot mirrors
  apt_repository:
    repo: "{{item}}"
    state: present
  loop:
    - deb http://nexus:8082/repository/apt-kubernetes/ kubernetes-xenial main
    - deb http://nexus:8082/repository/apt-docker/linux/ubuntu {{ansible_distribution_release}} stable

- name: install kubernetes
  apt:
    state: present
    package:
      - kubeadm
      - kubelet
      - kubectl

- name: Configure permanent modules
  blockinfile:
    block: |
      br_netfilter
      overlay
    path: /etc/modules-load.d/containerd
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Configure current modules
  modprobe:
    name: "{{item}}"
  loop:
    - br_netfilter
    - overlay

- name: Configure sysctl
  ansible.posix.sysctl:
    name: "{{item.key}}"
    state: present
    value: "{{item.value}}"
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  loop:
    - key: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - key: net.bridge.bridge-nf-call-iptables
      value: 1
    - key: net.ipv4.ip_forward
      value: 1
    - key: vm.swappiness
      value: 0

- name: Create containerd config directory
  file:
    state: directory
    path: /etc/containerd

- name: Stat Config File
  stat:
    path: /etc/containerd/config.toml
  register: stat_config

- name: Get default containerd config
  shell: containerd config default
  register: config
  ignore_errors: true
  when: not stat_config.stat.exists

- name: Save default containerd config
  copy:
    content: "{{config.stdout}}"
    dest: /etc/containerd/config.toml
  register: copy_config
  when: not stat_config.stat.exists

- name: Edit containerd to use systemd
  lineinfile:
    path: /etc/containerd/config.toml
    insertafter: 'plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc'
    line: '          SystemdCgroup = true'
  register: cgroup

- name: Restart containerd
  service:
    name: containerd
    state: restarted
  when: copy_config.changed or cgroup.changed

- name: Configure kubelet cgroup driver
  copy:
    content: |
      ---
      # kubeadm-config.yaml
      kind: ClusterConfiguration
      apiVersion: kubeadm.k8s.io/v1beta2
      kubernetesVersion: 1.21
      ---
      kind: KubeletConfiguration
      apiVersion: kubelet.config.k8s.io/v1beta1
      cgroupDriver: systemd
    dest: /tmp/kubeadm-config.yaml

- name: Disable swap
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: noswap

- name: Turn off swap
  command: swapoff -a
  when: noswap.changed

- name: add ip to dns cluster name
  ipa_dnsrecord:
    record_name: k8s
    record_type: A
    record_value: "{{ansible_default_ipv4.address}}"
    ipa_pass: "{{ipaadmin_password}}"
    zone_name: deepthot.aa