    api_user: "{{ lookup('ansible.builtin.env','PROXMOX_USER')}}"
    api_password: "{{ lookup('ansible.builtin.env','PROXMOX_PASSWORD') }}"
    api_host: pve
    storage: h2gt2g-hosts
    clone: ubuntu-cloud
    size: 8G
    autostart: false