---

- name: Wait for automatic system updates
  become: yes
  shell: while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done;

- name: install required packages
  apt:
    state: present
    package:
      - emacs-nox
      - freeipa-client
      - autofs
      - nfs-kernel-server
      - direnv
      - qemu-guest-agent

- name: edit nsswitch to allow sss to access automount
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'automount:'
    line: "automount:\tfiles sss"

- hostname:
    name: "{{ ansible_hostname }}.deepthot.aa"
    use: systemd

- timezone:
    name: America/Phoenix
  register: timezone

- name: restart cron
  systemd:
    name: cron
    daemon_reload: true
    enabled: true
    state: restarted
  when: timezone.changed

- name: join domain
  include_role:
    name: freeipa.ansible_freeipa.ipaclient

- name: Fix Automount
  include_tasks: fix_automount.yaml
