version: '3.8'

services:
  web:
    container_name: writefreely-web
    image: writeas/writefreely:latest

    volumes:
      - web-keys:/go/keys
      - ./config.ini:/go/config.ini

    networks:
      - internal_writefreely
      - external_writefreely

    ports:
      - '8080:8080'

    depends_on:
      - writefreely-db

    restart: unless-stopped

  db:
    container_name: writefreely-db
    image: mariadb:latest

    volumes:
      - db-data:/var/lib/mysql/data

    networks:
      - internal_writefreely

    environment:
      - MYSQL_DATABASE=writefreely

    restart: unless-stopped
    
    secrets:
      - secrets

volumes:
  web-keys:
  db-data:

networks:
  external_writefreely:
  internal_writefreely:
    internal: true

secrets:
  secrets:
    file: ./secrets.env

